name 'liatrio_vault'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures liatrio_vault'
long_description 'Installs/Configures liatrio_vault'
version '0.1.0'
